### ISSUE TITLE
connection to DCH-S220 siren

### ISSUE THREAD

**Issue by magnum** [ldotlopez/ha-hnap-device#2]
how to connect? parameters? 

ip: is it the ip of the siren? it seems no more supported from dlink apps, i can only get it connected (i suppose) because the led turns green, but the d-link my home app (on iOS) cannot find it when it scans the net to search for it, i can only find the new device in devices' list on my router, so i'm using that ip...

username: ?

password: is this the pin of the siren

thank you 
Antonio

**Comment by ldotlopez** [comment]
Hi, 

All your guesses are correct:
  - IP is the device's IP or hostname (from router or app)
  - Username is admin. The integration uses 'admin' by default. I doubt there is any other valid user but I leave it open just in case.
  - Password is the device's PIN. Again, I leave the terminology more generic, just in case. HNAP cameras uses passwords instead of PINs

May be I need to clarify or document some more stuff, thank for your feedback

**Comment by magnum** [comment]
damn :-) it says pin is not correct, BUT it's the one written on the label attached to the device;
to you know some ports i can try to connect at a lower level from shell?

**Comment by ldotlopez** [comment]
You can use the underlaying client: https://github.com/ldotlopez/python-hnap
It should be already instaled in your home-assistant environment.

There is a text based test client: `python -m hnap` and some code at https://github.com/ldotlopez/python-hnap/issues/1
